koalaman/shellcheck

Setup.hs
ShellCheck.cabal

This replaces the default preSDist hook in Setup.hs with our own. The
only thing the new hook does is compile the man page using callCommand
from System.Process.
If Pandoc fails, the entire sdist process will fail, since
Extra-Source-Files in the cabal file now lists the man page.
This is preferable to a build hook, because Pandoc pulls in a huge
number of dependencies. It's better to build the man page once and
ship it than to require every user to build and install pandoc before
he can build ShellCheck.
This creates another TODO item: an install hook can now be used to
install the man page along with the rest of ShellCheck. But beware,
the "man path" can vary from system to system.

Add a pre-sdist hook to compile the man page (Github issue #247).

---

ShellCheck/Checker.hs
ShellCheck/Formatter/TTY.hs
ShellCheck/Interface.hs
shellcheck.hs

Add --color switch
This changeset adds a --color switch to `shellcheck`. It works in a
similar fashion to the option of the same name in GNU tools such as
`ls`:
* `--color` or, equivalently, `--color=always` prints text
using color codes, even if stdout is not a terminal;
* `--color=never` disables color;
* `--color=auto`, the same as not specifying a `--color` option at
all, will print in color when stdout is deemed to be a capable
terminal.
This switch is useful when using, for example, a color-aware pager:
one can use `shellcheck --color | less -R` to get scrollable, colored
text, whereas `shellcheck` would otherwise print without color codes.
Comments on the code are very welcome; I don't know how well this fits
in the existing codebase, etc. Also I didn't add any tests, although
it …

Add --color switch

---

ShellCheck/Analytics.hs

When using -p, parent directories will not be created with the mode
specified with -m and will instead be created using the default behavior
controlled by umask.

Add a warning when you mkdir with both -p and -m.

---

ShellCheck/Checker.hs
ShellCheck/Formatter/Format.hs
ShellCheck/Formatter/JSON.hs
ShellCheck/Interface.hs
ShellCheck/Parser.hs

This change makes PositionedComment and ParseNote contain end columns.
It additionally modifies the JSON formatter to show the end column in an
"endColumn" property. SC1035 is then modified to set this end column.
Currently, all other checks set the end column to the start column.
Additional work is needed to set the end column during AST analysis.

Make SC1035 emit an end column

---

ShellCheck/Formatter/JSON.hs

This handles the case where the end line is not on the same line as the
start line when using the new end column feature.

Emit the end line in the JSON

---

Dockerfile

Similar to #720 but will build from the current source.  Run with docker run -i shellcheck < /path/to/script

add Dockerfile that will build shellcheck

---

.travis.yml
Dockerfile
Dockerfile_builder

Provide Continuous Integration & Continuous Delivery solution to this repository.
The changes include:
- **./Dockerfile_builder** is used to build shellcheck from source and collect executable shellcheck binary and object dependencies into a directory for easy retrieval. When it runs, the binaries will be copied out to the mounted directory.
- **./Dockerfile** is used to build the image that is based on `alpine:latest` and contains only the neccessary binaries for shellcheck to run. The entry point of the image is shellcheck program, and `/mnt` is the designated mount point when using this image as a CLI program.
- **./.travis.yml** Travis CI build script. The commit to this repo will trigger the build process, so we will know if it succeeds or fails. If the build succeeds, the final, …

Add CI/CD solution with Docker

---

.travis.yml

It is nice that shellcheck has a Docker distribution now since #734 was merged. It is useful in some environments, for instance when using shellcheck in Travis builds.
As far as I can understand, it looks like the current setup will only push the latest build of HEAD of the master branch to the `latest` tag in Dockerhub though. I think it would be useful if the releases were also tagged in Dockerhub so that you can point to a release version when using the Docker distribution of shellcheck e.g. `docker run koalaman/shellcheck:v0.4.5`.
This change *should* do just that, but it is a bit difficult to test. :) 
It looks like Travis will set `$TRAVIS_TAG='git_tag'` and `$TRAVIS_BRANCH='git_tag'` if the build was initiated by pushing a tag to the git repo. (see …

Push git tags to dockerhub as docker tags

---

ShellCheck/AST.hs
ShellCheck/Analytics.hs
ShellCheck/Parser.hs

Fixes koalaman/shellcheck#562. Special characters inside braces are
parsed into T_ParamSubSpecialChar instead of T_Literal so that they are
not flagged in the function checkInexplicablyUnquoted when sandwiched
between double quotes.

Add handling for special characters in parameter substitutions.

---

ShellCheck/Analytics.hs

always calling 'exit' is not good in e.g. functions.
the basic idea is at least that the returncode of
cd *is* evaluated somehow and not ignored.
Reported-by: Garance Alistair Drosehn <drosehn@rpi.edu>
Signed-off-by: Bastian Bittorf <bittorf@bluebottle.com>

SC2164: show two possible variants for circumenting the warning

---

ShellCheck/AST.hs
ShellCheck/ASTLib.hs
ShellCheck/Analytics.hs
ShellCheck/AnalyzerLib.hs
ShellCheck/Interface.hs

Implement some stylistic fixes based on HLint's suggestions: remove redundant parens, replace `liftM` with `fmap`, etc. It might be useful to add a `.hlint.yaml` file to the project to ensure high code quality.

Implement fixes suggested by HLint

---

README.md

Super minor documentation update, but for first-time cabal users we can avoid needing to compile twice because 'cabal test' won't run the first time we try.

add compilation documentation for test runners

---

ShellCheck/Analytics.hs

* Since `pushd` and `popd` have the same failure cases, make the check
for SC2164 apply to them as well.
* This commit also refactors the code a bit as `hasSetE` is now used in
multiple places.
* Fixes #863.
Signed-off-by: mr.Shu <mr@shu.io>

SC2164: Make SC2164 apply to `pushd` and `popd`

---

ShellCheck/AnalyzerLib.hs

Substring expansion detection only considers ':' as a separator..  It
needs to avoid triggering for ":-", ":=", ":+" and ":?", since they
mean other things.
This is a regression introduced by commit
a90b6d14b3de0f21db462afbc925444687feb2ca
Signed-off-by: Martin Schwenke <martin@meltin.net>

Fix incorrect detection of bash-style substring expansion (issue #950)

---

README.md

Installing haskell binaries is 50x faster than compiling it from source.

Documented binary cabal install for MacOS

---

ShellCheck/ASTLib.hs

Test file:
```
$ cat test.sh
#!/usr/bin/bash
function arrDeclare() {
declare -A arrd
arrd[foo]=bar
echo "${arrd[*]}"
}
function arrLocal() {
local -A arrl
arrl[fool]=bar
echo "${arrl[*]}"
}
function arrTypeset() {
typeset -A arrt
arrt[foot]=bar
echo "${arrt[*]}"
}
```
Before this fix:
```
$shellcheck test.sh
In test.sh line 10:
arrl[fool]=bar
^-- SC2154: fool is referenced but not assigned.
```
After this fix:
```
$shellcheck test.sh
```
Fixes koalaman/shellcheck#953
P.S. I'm not very familiar with the test frameworks or with Haskell, so I did not add any tests for these additional cases. I'll happily accept guidance to where and how that should be done!

SC2154: Fix false positive on `local`

---

ShellCheck/Analytics.hs
ShellCheck/AnalyzerLib.hs

The isClosingFileOp function expected closing file ops to use T_IoFile, but
they actually use T_IoDuplicate; so it effectively always returned False.
This fixes issue #862.

Fix isClosingFileOp (fixes issue #862)

---

README.md

Package is main repo of all versions. No need to add repository.

Update openSUSE instruction

---

snap/snapcraft.yaml

This adds configuration to build a snap package (https://snapcraft.io/)
To build, run `snapcraft` from the base directory.
The resulting snap can be installed with `sudo snap install --dangerous --classic <snapfile>`

Add snapcraft.yaml to build snap package

---

ShellCheck/Checks/Commands.hs

Fixes #327
SC2029 generates false positives when given an ssh command that includes
options with arguments because it assumes the first non-option must be the
host:port argument and the last argument is a command to run.
As suggested the comments on #327, this change fixes those by skipping the
check when there are any options present.

SC2029: Skip when there are options to ssh

---

ShellCheck/Analytics.hs

I felt bad about not adding a test for this in my original PR, so this should cover that behavior.
Follow-up to koalaman/shellcheck#988

Add test for `local` keyword in SC2154

---

README.md

We don't need to manually install ShellCheck on Travis CI now, it's a basic feature of Travis CI.
It's been a while since the end of 2016 :)
https://github.com/travis-ci/travis-cookbooks/pull/801/commits

[Docs] Update Travis CI part in README.md

---

nextnumber

Allows the use of the homebrew installed Bash 4 on MacOS systems. It
should compatible with most if not all modern Linux distros.

MacOS support for nextnumber

---

ShellCheck/Checks/Commands.hs

Favour the builtin `command -v` instead.
Rationale is discussed at https://stackoverflow.com/questions/592620/check-if-a-program-exists-from-a-bash-script.

Check for calls to `which`.

---

ShellCheck.cabal

custom-setup:
- http://cabal.readthedocs.io/en/latest/developing-packages.html#custom-setup-scripts
- https://www.well-typed.com/blog/2015/07/cabal-setup-deps/
Bounds:
- containers-0.5 is required if Data.Map.Strict
- parsec-3.0 for Text.Parsec
- json-0.3.6 for makeObj
---
I (as [Hackage Trustee](https://github.com/haskell-infra/hackage-trustees)) [revised](https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md) the bounds http://hackage.haskell.org/package/ShellCheck-0.4.7/revisions/ So no release is needed because of these changes.

Add custom-setup stanza and containers lowerbound

---

README.md

Shellcheck in default Travis builds is currently a version behind

README - Travis script for updating shellcheck ver

---

src/ShellCheck/Checks/ShellSupport.hs

[type](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/type.html) *is* defined by POSIX, and even the bourne shell has the `type` command.

Consider type a valid command in sh

---

.gitignore
README.md
snap/snapcraft.yaml

This pull request adds some improvements regarding to the snap packaging:
commit 366dc5d3f8b56166df8aa7406794019280e5a071
Author: 林博仁(Buo-Ren Lin) <Buo.Ren.Lin@gmail.com>
Date:   Thu Mar 29 20:24:31 2018 +0800
Add snap install instructions to README
Currently shellcheck is only provided by the edge channel, should remove the --channel argument after it is in candidate/stable.
Signed-off-by: 林博仁(Buo-Ren Lin) <Buo.Ren.Lin@gmail.com>
commit 1ed743e4101b12c54ed05c53d5b58a6336cc1c24
Author: 林博仁(Buo-Ren Lin) <Buo.Ren.Lin@gmail.com>
Date:   Thu Mar 29 20:05:52 2018 +0800
Add snapcraft generated files to the Git tracking ignore rules
This patches uses the following gitignore syntax so that only entries in the root folder is ignored, it is suggested to apply it to existing rules as well.
```
A …
```

Improve snap packaging

---

ShellCheck.cabal
shellcheck.hs
src/ShellCheck/AnalyzerLib.hs

Currently, shellcheck fails to build with ghc-8.4.1. This fixes that, while maintaining compatibility with ghc-7.8.4.

Bump to ghc 8.4.1

---

src/ShellCheck/Checks/Commands.hs

When given a %* format string, expect one more argument

---

src/ShellCheck/Parser.hs

While looking at #1175 (sorry to say I don't have a fix for it yet), i found this unused combinator. `cabal test` passes.

Remove unused code

---

src/ShellCheck/Analytics.hs

Add rename [0] to the list of commands that we don't check single quoted variables.
[0] http://man7.org/linux/man-pages/man1/rename.1.html

Whitelist rename for SC2016 (fixes #1199)

---

src/ShellCheck/AST.hs
src/ShellCheck/Checks/ShellSupport.hs
src/ShellCheck/Parser.hs

Fixes #1181 
Id is not used in T_Include, but I figured i'll leave it there so functions like getId don't have to change.

Add T_SourceCommand to wrap source commands and sourced code

---

src/ShellCheck/ASTLib.hs
src/ShellCheck/Analytics.hs

This adds an additional check, if name of command is `builtin`, we check if the first "flag" is one of the unchecked commands we are about.

Check if builtin cd is called

---

README.md

If a user wants to install a fixed version of `shellcheck` on a linux system, it was not obvious where to find the instructions.
This PR adds some documentation about that in the `README.md` file

Add instructions to install linux binary

---

src/ShellCheck/Parser.hs

Fixes #1268 
This checks that when the T_NormalWord read in a unary cond ends in a ']' that we did not have a starting '[', which would signify that this is an array index.

Fix false positive when indexing into array in cond

---

src/ShellCheck/Parser.hs

'@' was previously mentioned in 895ba3133783e23e3031f1991cfa63c154c79dce as a character needed to fix #909, but was not included in the actual change at that time.

Fix #949 (failing on @ in function names)

---

shellcheck.hs
src/ShellCheck/Analyzer.hs
src/ShellCheck/AnalyzerLib.hs
src/ShellCheck/Checker.hs
src/ShellCheck/Formatter/Format.hs
src/ShellCheck/Formatter/JSON.hs
src/ShellCheck/Interface.hs
src/ShellCheck/Parser.hs

Create a new data type Fix that represents suggested fix for a warning. Right now there is only one variant, which is a Surround String, representing a fix that surrounds the warning with a string.
This is created using `makeCommentWithFix`
Also worked on making the data types in interface more opaque, exposing all the record accessor functions. Not sure if this is alright, please take a look?

Make data in Interface more opaque

---

README.md

I've recently created the flymake-shellcheck package for Emacs, which allows using ShellCheck with the built-in Flymake package.
This commit adds a link (https://github.com/federicotdn/flymake-shellcheck) to the `flymake-shellcheck` GitHub page, which contains installation instructions.

Add link to flymake-shellcheck under Emacs section

---

src/ShellCheck/Analytics.hs
src/ShellCheck/AnalyzerLib.hs

It used to only treat all trailing variables in read as varaible
declarings, but an array variable can be declared in other positions:
read -a foo -r
foo is a declared variable, and multiple such variables can be declared.

Understand array variable declaration in read (fixes #679)

---

Dockerfile

Ref:
> Ubuntu 17.10 (Artful Aardvark) End of Life reached on July 19 2018
https://fridge.ubuntu.com/2018/07/19/ubuntu-17-10-artful-aardvark-end-of-life-reached-on-july-19-2018/

Update Docker build-only image to Ubuntu 18.04

---

src/ShellCheck/Checks/ShellSupport.hs

Values are retrieved from https://linux.die.net/man/1/dash, search for
ulimit.
Fixes #1406

Update supported ulimit flags for dash

---

src/ShellCheck/Checks/Commands.hs

This addresses Issue https://github.com/koalaman/shellcheck/issues/1404
Some grep flags support globs; these are now all checked to prevent false positives. Unit test cases for each flag were added.
```
I leaf@aspen ~/l/shellcheck (issue_1404_grep_globs=)> stack test
...
```

Issue 1404 grep glob false positives

---

src/ShellCheck/Analytics.hs

Issue https://github.com/koalaman/shellcheck/issues/1318
The case in which a single comma, with no spaces, used in an array assignment is now caught for SC2054. A new unit test case was added too.
```
I leaf@Sequoia ~/shellcheck (issue_1318_single_comma_array=)> stack test
...
```
```
I leaf@Sequoia ~/shellcheck (issue_1318_single_comma_array=)> cat /tmp/example.sh
#!/bin/bash
nowarn=(
abc,def
ghi,jkl
)
warn=(
abc,def,ghi
jkl,mno,pqr
)
echo "${nowarn[@]}"
echo "${warn[@]}"
```
- only the second example is caught
```
I leaf@Sequoia ~/shellcheck (issue_1318_single_comma_array=)> shellcheck /tmp/example.sh
In /tmp/example.sh line 8:
warn=(
^-- SC2054: Use spaces, not commas, to separate array elements.
For more information: …
```

Issue 1318 single comma array delimiter

---

src/ShellCheck/AST.hs
src/ShellCheck/Analytics.hs
src/ShellCheck/AnalyzerLib.hs
src/ShellCheck/Data.hs
src/ShellCheck/Parser.hs

This is motivated by the fact that the popularity of bats is increasing
since the creation of bats-core/bats-core.
The code is a cherry-pick of [koalaman/shellcheck/bats](/koalaman/shellcheck/tree/bats/) branch.
Fix koalaman/shellcheck#417.

Add bats support

---

src/ShellCheck/Checks/Commands.hs

Issue https://github.com/koalaman/shellcheck/issues/824
Fix up to original change to include '--fixed-strings' in the grep +
regex special cases.
```
I leaf@Sequoia ~/w/shellcheck (issue_824_grep_fixed_strings=)> stack test
...
=== prop_readScript5 from src/ShellCheck/Parser.hs:2975 ===
+++ OK, passed 100 tests.
```

Issue 824 grep fixed strings and SC2063

---

shellcheck.1.md
shellcheck.hs
src/ShellCheck/Checker.hs
src/ShellCheck/Interface.hs

Issue https://github.com/koalaman/shellcheck/issues/837
Add an --include option, which creates a whitelist of warnings to report
on, the opposite of --exclude.
```
stack exec -- shellcheck --help
Usage: shellcheck [OPTIONS...] FILES...
-a                --check-sourced          Include warnings from sourced files
-C[WHEN]          --color[=WHEN]           Use color (auto, always, never)
-i CODE1,CODE2..  --include=CODE1,CODE2..  Consider only given types of warnings
-e CODE1,CODE2..  --exclude=CODE1,CODE2..  Exclude types of warnings
-f FORMAT         --format=FORMAT          Output format (checkstyle, gcc, json, tty)
-s SHELLNAME      --shell=SHELLNAME        Specify dialect (sh, bash, dash, ksh)
-S SEVERITY       --severity=SEVERITY      Minimum severity of errors to consider (error, …
```

Issue 837 flag to include only certain warnings

---

src/ShellCheck/Checks/ShellSupport.hs

The only acceptable flags for the `unset` builtin under POSIX sh and dash
are [-fv] ([see spec](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#unset)). Bash though, accepts [-n] too. This commits makes shellcheck
warn about this.

Check unset flags under dash and POSIX sh

---

src/ShellCheck/Checks/ShellSupport.hs

Flags for the hash builtin other than `[-r]` are undefined under POSIX sh.
Dash also accepts `[-v]`, while bash adds `[-l] [-p filename] [-dt]` aside
from `[-r]`.

Check hash flags under dash and POSIX sh

---

src/ShellCheck/Checks/ShellSupport.hs

Flags for the `wait` builtin are undefined under both POSIX sh ([see spec](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/wait.html)) and dash. Bash though, accepts `[-fn]`.

Check wait flags in dash & POSIX sh

---

src/ShellCheck/Analytics.hs
src/ShellCheck/AnalyzerLib.hs

Now ShellCheck recognises array variables assigned by `printf -v`.
`stack build && stack test`
```
=== prop_checkUnassignedReferences37 from src/ShellCheck/Analytics.hs:1957 ===
+++ OK, passed 1 tests.
...
```

Fix issues #896 and #433: printf -v and arrays

---

shellcheck.hs
src/ShellCheck/Interface.hs
src/ShellCheck/Parser.hs

Add a new optional flag `-r|--root ROOTPATHS`, where `ROOTPATHS` is a colon separated list of paths, that will look for external sources in alternate roots.
This is particular useful when the run-time environment does not fully match the development environment. The `#shellcheck source=file` directive is useful, but has its limitations in certain scenarios. Also, in many cases the directive could be removed from scripts when the root flag is used.
Script example.bash:
```bash
#!/bin/bash
source /etc/foo/config
```
Example usage where `etc/foo/config` exists in `skel/foo`:
```bash
shellcheck -x -r skel/foo:skel/core example.bash
```

Add option to look for sources in alternate root paths

---

README.md

The sdist hook in [Setup.hs](Setup.hs) disables the `smart` extension
when creating man page.
```console
pandoc -s -f markdown-smart -t man shellcheck.1.md -o shellcheck.1
```

docs: README: Update pandoc command to match `Setup.hs`

---

CHANGELOG.md
shellcheck.1.md
shellcheck.hs
src/ShellCheck/Formatter/Format.hs
src/ShellCheck/Formatter/JSON.hs

Add a new -t option to specify the output width of tabstops, with a
default of 8 to match the current behavior.  Convert formatters that
currently use hardcoded 8-character tabstops (TTY and JSON) to respect
the new -t option.
This has two main use cases:
1. Allow editors to pass -fjson -t1 so that they can consume the json
output in a character-oriented way without breaking backwards
compatibility.
2. Allow users with narrow terminals to run
shellcheck -tN | expand -tN
to fit more levels of indentation on the screen.
Also addresses #1048.

Allow variable tabstop widths

---

CHANGELOG.md
src/ShellCheck/AST.hs
src/ShellCheck/ASTLib.hs
src/ShellCheck/Analytics.hs
src/ShellCheck/AnalyzerLib.hs
src/ShellCheck/Checks/Commands.hs
src/ShellCheck/Checks/ShellSupport.hs
src/ShellCheck/Data.hs
src/ShellCheck/Parser.hs

This uses the new verbose warning level to add SC2250 as a new check to require braces around variable references.  Additional reasoning for this warning is in the individual commit message.

New verbose check for braces around variable references

---

README.md
shellcheck.1.md
shellcheck.hs
src/ShellCheck/AST.hs
src/ShellCheck/ASTLib.hs
src/ShellCheck/Analytics.hs
src/ShellCheck/Analyzer.hs
src/ShellCheck/AnalyzerLib.hs
src/ShellCheck/Checker.hs
src/ShellCheck/Checks/Commands.hs
src/ShellCheck/Formatter/CheckStyle.hs
src/ShellCheck/Formatter/Format.hs
src/ShellCheck/Formatter/GCC.hs
src/ShellCheck/Formatter/JSON.hs
src/ShellCheck/Formatter/TTY.hs
src/ShellCheck/Interface.hs
src/ShellCheck/Parser.hs
src/ShellCheck/Regex.hs

Update Copyright to year 2019; README linting

---

src/ShellCheck/Analytics.hs

When using '``' or '```', it should not suggest using double quotes.
My use case was printing slack code blocks:
```
echo '```'"$DIFF"'```'
```

SC2016: Don't trigger when using empty backticks

---

CHANGELOG.md
src/ShellCheck/Analytics.hs
src/ShellCheck/AnalyzerLib.hs
src/ShellCheck/Data.hs

The shflags command-line flags library creates variables at runtime
with a few well-defined functions.  This causes shellcheck to spit out
lots of warnings about unassigned variables, as well as miss warnings
about unused flag variables.
We can address this with two parts:
1. Pretend that the shflags global variables are predefined like other
shell variables so that shellcheck doesn't expect users to set them.
2. Treat DEFINE_string, DEFINE_int, etc. as new commands that create
variables, similar to the existing read, local, mapfile, etc.
Part 1 can be addresssed without this by following sourced files, but
that doesn't help if people are otherwise not following external
sources.
The new behavior is turned on by a new --uses-shflags command-line
parameter.
Addresses #1597

Add support for basic shflags semantics

---

shellcheck.1.md

Out of interest, I ran the command
pandoc -s -f markdown-smart -t man shellcheck.1.md -o shellcheck.1
locally, but that produces warnings (previous to this commit).  Checking
the generated manpage, I found the diff to be rendered very badly.
(Broken at terminal width like a normal paragraph).  This commit fixes
the problem.

Fix syntax and indentation in shellcheck.1.md

---

src/ShellCheck/Analytics.hs

Resolve #1709
This PR checks if the command is exactly `read -t 0`, if so then just ignore `-r` requirement for `read` command since it has specific purpose for checking if there is any input to be read.
If used for other means, eg. piping file directly to the command, `-r` is still required since it's not being used as an input detector anymore.

Allow `read -t 0` to not require -r flag

---

CHANGELOG.md
src/ShellCheck/Analytics.hs

SC2247 already warns about translated strings that look like $"(foo)" or
$"{foo}".  Since typical use of translated strings is to translate whole
messages, a string like $"foo" is likely to be a similar mistake if foo
is the name of an existing variable.  Conversely, a string like
$"foo bar" is potentially meant to be a message id even if foo is a
known variable.
Add a warning for the $"foo" case, but make it separate from the
existing warning so that projects that reuse variable names as their
message ids can separately disable the new warning.

SC2256: Check for translated strings matching known variables

---

src/ShellCheck/Analytics.hs

test.sh:
```
#!/usr/bin/env bash
set -o errexit
export FOO="$(myEnvBuilder)"
FOO="$(myEnvBuilder)" ./myCmd.sh
```
output of `shellcheck test.sh`:
```
In test.sh line 3:
export FOO="$(myEnvBuilder)"
^-^ SC2155: Declare and assign separately to avoid masking return values.
In test.sh line 4:
FOO="$(myEnvBuilder)" ./myCmd.sh
^-^ SC2155: Declare and assign separately to avoid masking return values.
[...]
```
---
`stack test`:
```
[...]
=== prop_checkMaskedReturns6 from src/ShellCheck/Analytics.hs:2791 ===
+++ OK, passed 1 test.
[...]                              
ShellCheck-0.7.0: Test suite test-shellcheck passed
```

Fix issue #1733 (False negative in SC2155)

---

src/ShellCheck/Parser.hs

Fixes #1650
Proudly made by @gabrielelana, @sphaso and @muzietto at Open Source Saturday 
[![Open Source Saturday](https://img.shields.io/badge/%E2%9D%A4%EF%B8%8F-open%20source%20saturday-F64060.svg)](https://www.meetup.com/it-IT/Open-Source-Saturday-Milano/)

Support for heredoc quoted token like `'"FOO"`

---

CHANGELOG.md
src/ShellCheck/Analytics.hs
src/ShellCheck/AnalyzerLib.hs
src/ShellCheck/Checks/Commands.hs
src/ShellCheck/Parser.hs

Fix issue #1724 
Now shellcheck recognises read/written variables in builtins called with the 'builtin' keyword. The parser looks at the first argument passed to `builtin` to determine the type of the other arguments so `builtin cmd ...` is parsed in the same way as `cmd ...` and it automatically parses assignments correctly if the builtin is `export`, `declare`, etc.
With the second commit command-specific checks in `ShellCheck.Checks.Command` are applied to commands called with `builtin` in the same vein as the parser.
It might be useful to add a new warning for unknown builtins because as of now `builtin my-strange-cmd-which-isnt-a-builtin` doesn't trigger any. @koalaman if you agree with me, leave a reply on this message and I will add another commit on this pull request.
---
`stack …

Fix issue #1724 (bash: missing support for 'builtin' keyword)

---

README.md

shellcheck comes installed by default on github's linux VM
https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions

add github actions link

---

.compile_binaries

Symlink was failing due to pre-existing target file:
sudo ln -s /usr/local/bin/gsha512sum /usr/local/bin/sha512sum
ln: /usr/local/bin/sha512sum: File exists
Build is passing now https://travis-ci.org/ArturKlauser/shellcheck/builds/630262030

Fix OSX build on Travis

---

.travis.yml

Fixing the following Travis build config validation warnings:
* root: deprecated key sudo (The key `sudo` has no effect anymore.)
* root: missing os, using the default linux
* deploy: key local-dir is not underscored, using local_dir
* language: value sh is an alias for shell, using shell
* root: key matrix is an alias for jobs, using jobs
The linux builds pass https://travis-ci.org/ArturKlauser/shellcheck/builds/630319022
the osx build is broken for a different reason #1783.

Fix Travis warnings

---

README.md

Pre-compiled binary URL for aarch64 was linked to armv6hf.

README.md: Fix pre-compiled binary URL for aarch64

---

.compile_binaries
.multi_arch_docker
.travis.yml
Dockerfile
Dockerfile.multi-arch

This builds the docker images as multi-architecture images, which is a recent feature supported by docker's buildx extension. The corresponding Dockerfile simply reuses the shellcheck binaries that are already built and deployed for multiple architectures. See how my [test images](https://hub.docker.com/repository/docker/arturklauser/shellcheck-alpine/tags?page=1) report availability for multiple architectures. Each client pulling from Docker Hub automatically pulls only the appropriate architecture version for itself, so there is no additional overhead for the client. Clients don't need experimental features enabled (only the builder need them).
The docker build and deployment is hooked into the existing Travis CI/CD pipeline, conditioned on all other builds and tests passing. You can …

Add multi-architecture Docker image build

---

ShellCheck.cabal

We've actually already required base >= 4.8.0.0 since commit a8376a0 (in which we first used `<$>` without an import, which wasn't in the Prelude prior to this version). Since then, we've also made use of other more substantial features that de-facto require base >= 4.8.0.0 since they require GHC 7.10, such as `DeriveAnyClass`.

Mark that base >= 4.8.0.0 is required

---

.travis.yml

For security reasons, PR runs don't have access to Travis secrets. However,
Docker deployment depends on the secret DOCKER_PASSWORD. Thus we shouldn't try
Docker deployment when running PRs since it will fail for lack of access.
This fixes #1884

Don't try to deploy docker images on PR runs

---

.travis.yml

Since the deploy step is in the Travis file global context, it runs for every stage. However, it only makes sense to run for the Build stages which actually prepare something to deploy.

Run "deploy" step only for "Build" stages

---

src/ShellCheck/Analytics.hs
src/ShellCheck/AnalyzerLib.hs

This fixes #1758 and adds a test for it.
for reference, commit 4fc48998037fd52c07c29b62cf25584ba738cead introduced the `:=` variant, and 3c5c74ff047ba99451b3a1a7689f5c1b84d1634b adds (broken) support for both variants (but misses this place).

recognize `: ${parameter=word}` as assignment

---

src/ShellCheck/ASTLib.hs
src/ShellCheck/Analytics.hs
src/ShellCheck/AnalyzerLib.hs
src/ShellCheck/Checks/Commands.hs
src/ShellCheck/Checks/ShellSupport.hs

`bracedString` is a dangerous partial function, and it's simple enough to replace it with its safe equivalent everywhere possible. Do that everywhere except for `isDefaultAssignment` in `checkSpacefulness`, where I don't see a way to prove that it's actually always safe. Also, move its definition there so that no new uses of it appear.

Mostly get rid of bracedString

---

src/ShellCheck/Formatter/GCC.hs
src/ShellCheck/Formatter/JSON1.hs
src/ShellCheck/Formatter/TTY.hs

We still support GHC 8.0, which didn't have fromRight.
This reverts commit 64c31d91422e3c48cc7ed0176b069fa11456cee8.

Revert "Use fromRight instead of reimplementing it"

---

README.md

The `shellcheck-static` AUR package has been removed and `shellcheck-bin` is an option for a dependency free AUR package.

update dependency free AUR package

---

src/ShellCheck/Parser.hs

The message "Can't follow non-constant source. Use a directive to specify location." set me off on the wrong foot. At first, I thought it meant "In bash, you can't source a script specified by a variable." It was only after reading the wiki page for this message https://github.com/koalaman/shellcheck/wiki/SC1090 that I understood that the problem is that *shellcheck* can't check the sourced file. So I would suggest to rephrase this message so that it is more clear that the problem is in the checking, not in the running of the script.

Rephrase: *Shellcheck* can't follow non-constant source

---

snap/snapcraft.yaml

The snap runtime only ships the C.UTF-8 locale, as other locales don't seem to be used just hardcode it for now.
Signed-off-by: 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>

Fix snap distribution unable to process scripts in Unicode(Chinese) (fixes #1643)

---

src/ShellCheck/Analytics.hs
src/ShellCheck/AnalyzerLib.hs

https://github.com/koalaman/shellcheck/issues/1759
When a simple process substition is used, this tripped up
the getMapfileArray function by making the last argument
not a variable
Build!
```
~/w/s/shellcheck (issue_1759_mapfile_proc_substition=)> stack build
~/w/s/shellcheck (issue_1759_mapfile_proc_substition=)> echo $status
0
```
Test!
```
~/w/s/shellcheck (issue_1759_mapfile_proc_substition=)> stack test
...
=== prop_readScript5 from src/ShellCheck/Parser.hs:3105 ===
+++ OK, passed 1 test.
ShellCheck-0.7.0: Test suite test-shellcheck passed
I leaf@alder ~/w/s/shellcheck (issue_1759_mapfile_proc_substition=)> echo $status
0
```

Issue 1759 mapfile and process substition

---

src/ShellCheck/Analytics.hs

This adds a warning for readonly masking the return value of function.
This is mentioned in the wiki
https://github.com/koalaman/shellcheck/wiki/SC2155#problematic-code-in-the-case-of-readonly
but didn't actually produce a warning.
Fixes https://github.com/koalaman/shellcheck/issues/1336

Add readonly to SC2155

---

README.md

Thought it was worth mentioning MacPorts as an installation option on macOS.

Add MacPorts as installation option in README.md

---

src/ShellCheck/Parser.hs

The `env` command has a `-S,--split-string` option which enables having arguments for the command in a shebang.
Also, one can use variable assignments for the command since `env` treats only the first word without a `=` character as the
program to run.
Fixes #2143.

Allow `env` to have flags and variables in shebang

---

src/ShellCheck/Analytics.hs

Same as 08d2eef4111afde4 but for podman.
Fixes https://github.com/koalaman/shellcheck/issues/2057

Whitelist podman for SC2016 about '$var'

---

build/windows.x86_64/Dockerfile

when building for windows there are many error message like below
```
003a:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
```

suppress ntlm error messages in Windows build

---

src/ShellCheck/Parser.hs

- Report error in case of a backspace in a comment
Backspaces in comments are no good. In most cases they are the result of
commenting out a longer line, that was broken down. This usually results
in the shell treating the following lines as their own commands on their
own lines instead of as parts of the longer, broken down line.
There are counter examples, but their usage of the backslash to break the line is rather academic anyways.
The following will result in an error:
```
echo "bla 1" \
#&& echo "bla 2" \
&& echo "bla 3"
```
The following would be the output for the example above:
```
In backslash.sh line 2:
echo "bla 1" \
^-- SC1073: Couldn't parse this simple command. Fix to allow more checks.
In backslash.sh line 3:
#&& echo "bla 2" \
^-- SC1072: Backslash in or directly after …
```

Error on backslash in comment

---

src/ShellCheck/Parser.hs

- SC1036
- My shellcheck version 0.7.2 and "online"
```sh
#!/bin/bash
f,unc() { echo hello world; }
f,unc
```
```
In /tmp/1.sh line 2:
f,unc() { echo hello world; }
^-- SC1036: '(' is invalid here. Did you forget to escape it?
^-- SC1088: Parsing stopped here. Invalid use of parentheses?
For more information:
https://www.shellcheck.net/wiki/SC1036 -- '(' is invalid here. Did you forg...
https://www.shellcheck.net/wiki/SC1088 -- Parsing stopped here. Invalid use...
```
Nothing, code is valid. Bash has _very_ relaxed rules for function names and comma is also allowed in function names.

Add a comma to function characters

---

ShellCheck.cabal

Use extra-doc-files (available in Cabal 1.18 and later) and include the CHANGELOG in releases
(then it will be visible on Hackage, etc)

move readme to extra-doc-files and add changelog to releases

---

src/ShellCheck/Analytics.hs
src/ShellCheck/AnalyzerLib.hs

This PR provides an enhancement very similar to the one described in #2054. The following example is copied from that issue:
```bash
#!/bin/bash
set -e
foo() {
set -e
false
echo "output after failed command even with set -e"
}
if foo; then
echo
fi
```
The current version of `shellcheck` provides no notice, although this PR produces the following:
```
if foo; then
^-^ SC2304: This function invocation will run with set -e disabled.
For more information:
https://www.shellcheck.net/wiki/SC2304 -- This function invocation will run...
```
It also handles all the other cases (that I know of) where `set -e` can be disabled during a function call. The new notice can be suppressed by inserting `set -e` into the correct context. For example this program produces an error in `shellcheck`:
```bash …
```

Show info about `set -e` suppression during function calls

---

src/ShellCheck/Analytics.hs

`grep -c` counts the number of matches, and `grep -l/-L` outputs the names of the files with/without matches. Now, if I want the number of files with/without matches, I would write something like this:
```sh
grep -li "fail" ./*.log | wc -l
```
However, Shellcheck suggests replacing the `grep -l/-L | wc -l` with `grep -c`, which is not the correct solution:
```
Line 3:
grep -li "fail" ./*.log | wc -l
^-- SC2126: Consider using grep -c instead of grep|wc -l.
```
Therefore, I have added `-l/-L` to the blacklist of `grep` options that prevent [SC2126](https://github.com/koalaman/shellcheck/wiki/SC2126) from being issued.

Do not suggest `grep -c` as a replacement for `grep -l/-L | wc -l`

---

src/ShellCheck/Analytics.hs
src/ShellCheck/AnalyzerLib.hs
src/ShellCheck/Checks/Commands.hs
src/ShellCheck/Data.hs

Adds the check mentioned here, plus related ones: https://github.com/koalaman/shellcheck/pull/2303#discussion_r698056295 Example:
`/tmp/a.sh`:
```bash
#!/usr/bin/env bash
set -e
readarray -t files < <(ls)
echo "${files[@]}"
```
```
% ./quickrun /tmp/a.sh --enable=check-extra-masked-returns
Up to date
In /tmp/a.sh line 3:
readarray -t files < <(ls)
^-- SC2312: Consider invoking this command separately to avoid masking its return value (or use '|| true' to ignore).
For more information:
https://www.shellcheck.net/wiki/SC2312 -- Consider invoking this command se...
```

Add extra checks for masked return codes

---

src/ShellCheck/Analytics.hs

Using `--after-context`/`-A` or `--before-context`/`-B` would give a warning
recommending the user to use `grep -c`, even though that would give a different
result than using `grep | wc -l`:
```fundamental
$ echo -e "1\n2\n3" | grep -cA 3 1
1
$ echo -e "1\n2\n3" | grep -A 3 1 | wc -l
3
```

Fix bug in 2126 when using after/before flags with grep

---

.github/workflows/build.yml

This PR updates GitHub Actions to their latest major versions. Main change is they are all now using Node 16 internally instead of 12, which was EOL at the end of April.
- Changelog for `actions/checkout` can be [found here](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- Releases for `actions/upload-artifact` can be [found here](https://github.com/actions/upload-artifact/releases)
- Releases for `actions/download-artifact` can be [found here](https://github.com/actions/download-artifact/releases)

ci: update github actions

---

src/ShellCheck/Checks/Commands.hs

SC2183 grammer fix: 'variable' instead of 'variables' if only one variable

---

src/ShellCheck/Analytics.hs

ShellCheck throws warning SC2093 when a script contains commands that could never be executed because they are after an `exec`.  Command `:` does nothing, so add it to the list of commands that don’t trigger this warning.

Permit colon after exec

---

README.md

Trunk Check is a universal linter which integrates with a wide variety of linters and formatters, `shellcheck` included.
We're big fans of `shellcheck` and figured that you might find our tool to be interesting enough to include it in the integrations list.
---
We did previously reach out in #2618 and came off a little strong - wanted to say sorry again about that; it wasn't necessarily in the best taste.

Document Trunk Check integration

---

README.md

These binaries are repackaged in .tar.gz format for a more portable installation, and also comes with the Apple M1 binary.

Mention VS Code ShellCheck binaries distribution

---

src/ShellCheck/Parser.hs

fish is a decently popular shell, so let's add it to the recognized unsupported shells

Add fish to the badShells list

---

ShellCheck.cabal

The whole test suite passes for me, including prop_checkOverwrittenExitCode8, and I get the same set of findings with this build and shellcheck.net on tools/testing/selftests/net/icmp_redirect.sh.

Fix #2734: adjust bounds to compile on 9.6

---

src/ShellCheck/Analytics.hs

* The short description used to say that until commit aac7d76047a5b28d064b17a5d0fac022054d05a0 from 2014. It appears that it was changed by mistake in that commit to something less readable.
* With the message "use -print0/-0" we were confused and introduced a bug in our code because we didn't understand what to do with the "-0".
* SC2011 (source https://github.com/koalaman/shellcheck/blob/c9e27c24700cdc5b84cfca1f7a90fe07f542867c/src/ShellCheck/Analytics.hs#L591) uses that exact warning message, we copied it from there.
cc: @swalchemist

improve short description for SC2038

---

CHANGELOG.md
src/ShellCheck/Checks/ShellSupport.hs

Hi @koalaman, @josephcsible :wave: 
Big fan of shellcheck, loving it, using regularly, evangelizing even as a linter that doesn't suck (~unlike pylint~), that is produces actually useful output. FWIW, good license choice too... respected.
So, I was scripting a thing today, something that should've worked both in zsh and bash, and stumbled on an issue. Perfect chance to give back by contributing!
[SC3014][] warns about `[ foo == bar ]` being a bashism, not posix-compatible. However, it doesn't catch `test foo == bar`.
This little patch fixes that, and also exactly similar bashism checks SC3012–3017. 
I'm also adding tests.
Please review. Not sure this is the best way to fix it — there's fair bit of duplication, also `ViewPatterns` might not be to everyone's taste (though I like it). …

Fix: extend []-related bashism checks on `test` calls too

---

.gitignore
test/shellcheck.hs

This also fixes the problem that the testsuite threw `exitFailure`
even when it succeeded (which I found inexplicable).
Once this is published, the testsuite could be enabled in Stackage again.

Testsuite: report which module failed the tests

---

README.md

ShellCheck is now available on winget, so we can add it to the installation methods.
Fixes #2691

Add installation directions for winget

---

README.md

This command does not work anymore and it seems that a `cabal test` is sufficient without an install beforehand.

Remove deprecated "install --enable-tests" command

---

shellcheck.1.md
shellcheck.hs

This introduces the "--rcfile" argument which allows a specific shellcheckrc file to be passed.
If specified and the given file exists, the default locations will not be searched and the specified file will be used.

Implement rcfile option

---

README.md

Since Microsoft acquired GitHub and discontinued Atom in 2022, the community started a fork at https://pulsar-edit.dev/. Linking to an archived repository under the Atom organization does not make sense anymore, so link to active Pulsar fork instead.
The Pulsar Edit history is explained at length in https://optimizedbyotto.com/post/pulsar-best-text-file-and-code-editor/.

Replace Atom reference with Pulsar Edit equivalent

---

README.md

Currently README file doesn't include the macOS Arm64 pre-compiled binaries link.
This PR just adds that link for clarity.

Update README.md to add macOS Arm64 pre-compiled binaries link

---

build/linux.aarch64/Dockerfile
build/linux.x86_64/Dockerfile

This reduces the size of the Linux x86_64 binary from 15 megabytes to 5.8 megabytes and fixes the build for Linux aarch64.
Building with `alpine:latest` creates a binary of 29 megabytes, but when building with `alpine:3.16` it's just 5.8 megabytes. I'm not sure, though, what piece of GHC, GCC/LLVM, etc. is causing the increased size.
The published build of ShellCheck 0.10.0 is 15 megabytes, instead of the expected 29 megabyes using the builder of this repo. Perhaps the container was still cached and based on an older version of `alpine`?
Attempting to build for Linux aarch64 failed with this message. Ubuntu Kinetic is not provided with updates anmore.
I'm not sure why the Linux binary for aarch64 is so much larger than for x86_64 (31 megabytes), but it's probably nothing I can fix. The …

Fix builders for Linux

---

src/ShellCheck/Analytics.hs

Bash has both `typeset` and `declare`, but ksh has `typeset` only. Recommend the more portable alternative to users.

Recommend `typeset` instead of `declare` in SC2324

---

src/ShellCheck/Checks/ShellSupport.hs

Busybox shell supports `$'..'`, `read -p <prompt>`, `type -p` and `echo -e` so remove the warnings there.

Fix SC3003, SC3036 and SC3045 for busybox shell

---

src/ShellCheck/AnalyzerLib.hs

These are being set by `run --separate-stderr` and have been introduced in https://github.com/bats-core/bats-core/releases/tag/v1.5.0

Add new bats variables stderr and stderr_lines

---

README.md

`shellcheck` seems to be available and working inside [Flox] today!
Since Flox is related to Nix, I thought it'd make sense to add it to the list. 😁
[Flox]: https://flox.dev/docs/

Add Flox to list of installation methods

---

src/ShellCheck/Data.hs
src/ShellCheck/Parser.hs

A portable version of OpenBSD's ksh is distributed with the executable name [oksh][1]. It's a descendant of pdksh and can be shellchecked as ksh.
[1]: https://github.com/ibara/oksh

Recognize "oksh" executable name as ksh

---

src/ShellCheck/Data.hs

From the bug-bash@gnu.org announcement "[Bash-5.3-beta available](https://lists.gnu.org/archive/html/bug-bash/2024-12/msg00120.html)":
> q. GLOBSORT: new variable to specify how to sort the results of pathname expansion (name, size, blocks, mtime, atime, ctime, none) in ascending or descending order.
> 
> w. BASH_MONOSECONDS: new dynamic variable that returns the value of the system's monotonic clock, if one is available.
> 
> x. BASH_TRAPSIG: new variable, set to the numeric signal number of the trap being executed while it's running.

Recognize internal variables new in bash 5.3

---

CHANGELOG.md
src/ShellCheck/Checks/ShellSupport.hs

<https://pubs.opengroup.org/onlinepubs/9799919799/utilities/test.html>
fix #3168

fix(SC3012)!: do not warn about `\<` and `\>` in test/[] as specified in POSIX.1-2024

---

src/ShellCheck/Checks/ShellSupport.hs

fix(SC3013): check POSIX-compliant unary operators for test and [

---

src/ShellCheck/Analytics.hs

In cases like 
```bash
#!/bin/sh
set -e
foo && bar || true
```
The last `true` is used for masking the return value, no matter if both `foo` and `bar` executed, therefore SC2015 has no relevance here.
Closes #2977

Skip SC2015 when the last command is true

---

src/ShellCheck/Parser.hs

My work environment has a some scripts that use python3 as the interpreter, not just /usr/bin/python.  Those scripts are mixed into the same directory as shell scripts.  None of these scripts, python, python3, or shell, contain a file extension to glob on.  There are specific reasons that some of these scripts use python vs python3, so changing the hashbang won't work for us.  Therefore, the smallest touch approach is to modify shellcheck to ignore files with python3 hashbangs.  I don't feel that this is a stretch or change of behavior since shellcheck already doesn't allow /usr/bin/python.

Add python3 to the list of badShells

---

CHANGELOG.md
src/ShellCheck/Checks/ShellSupport.hs

<https://pubs.opengroup.org/onlinepubs/9799919799/utilities/test.html>
fix #3167

fix(SC3013)!: remove SC3013 since the operators are specified by POSIX.1-2024

---

src/ShellCheck/Analytics.hs

- fix #3179 — negation of SC2055, `[ x = y -a x = z]`
- fix #3181 — negation of SC2056, `(( x == y && x == z ))`
- fix #3180 — negation of SC2252, `[ x = y ] && [ x = z ]`

feat: check tautologically-false conditionals

---

CHANGELOG.md
src/ShellCheck/Analytics.hs

suggest `[ a != b ]` over `[ ! a = b ]` and `! [ a = b ]`, and so forth. c.f. SC2236 and SC2237 (unary operations)
close #3164

feat: avoid double negative of a binary operator in test
