ShellCheck/Parser.hs
=> Added FlexibleContexts extension in Parser.hs to fix compilation.

README.md
I noticed a few typos while reading through your README - they should be fixed here.
=> Fix a handful of typos.

README.md
It was missing from the list. I thought it was best to add it. :)
@koalaman, thanks for all your excellent work! I've found this tool to be a frequent aid in script development!
=> Add Gentoo to supported distribution list.

README.md
=> README.md: sort package managers, add emerge (Gentoo)

ShellCheck/Analytics.hs
Added check for wc's params when used with grep as has been suggested by the issue reporter. Also added a range of tests.
=> This commit fixes #797

README.md
=> Update README.md with installation instructions for EPEL distros

shellcheck.1.md
Was wishing for this feature, and poof! there it was already!  :-)
=> Document shell directive added by 944313c6

ShellCheck/Checks/Commands.hs
* Do not warn when `mkdir -pm 0700` is used with combination of paths
like `..` and `.`
* Fixes #854
Signed-off-by: mr.Shu <mr@shu.io>
=> SC2174: Do not warn at `mkdir -pm 0700 ../foo`

ShellCheck/Analytics.hs, ShellCheck/AnalyzerLib.hs
=> Recognize bash's `shopt -s lastpipe`

README.md
Added installation instructions for Solus distro.
=> Updated readme installation instructions

ShellCheck/Analytics.hs, ShellCheck/Data.hs
=> Extend SC2216/SC2217 with 'true' and 'false'

ShellCheck/Parser.hs
Solves https://github.com/koalaman/shellcheck/issues/1091
=> Use readVariableName combinator

Dockerfile, README.md
Use multi stage Dockerfile to greatly simplify build.
=> Simplify Dockerfile

README.md
See https://github.com/lukesampson/scoop/blob/master/bucket/shellcheck.json
=> Added scoop install

CHANGELOG.md, src/ShellCheck/Analytics.hs
Addresses https://github.com/koalaman/shellcheck/issues/1137
=> Warn about invalid arguments to sudo

src/ShellCheck/Analytics.hs
=> Add unset to list of commands exempt from 2016

ShellCheck.cabal, src/ShellCheck/Formatter/JSON.hs
Adds bytestring as a dependency for putStrLn encoded values.
=> Change to aeson (fixes #1085)

README.md
The dot after the screenshot in README.md is strange so this commit remove it.
=> Remove unnecessary dot

src/ShellCheck/Checker.hs, src/ShellCheck/Interface.hs, src/ShellCheck/Parser.hs
I saw your comment [0], I already did a bit of work, figured I might as well upload and see what you think about it :)
[0] https://github.com/koalaman/shellcheck/pull/695#issuecomment-392307999
=> End column

shellcheck.hs
=> Allow trailing comma in exclude flag

src/ShellCheck/Checks/Commands.hs
=> Use regex to match special flags for printf

Setup.hs
=> Disable smart typography extension for markdown input

src/ShellCheck/Fixer.hs, src/ShellCheck/Formatter/TTY.hs, src/ShellCheck/Interface.hs
=> Fix applying multiple fixes per line

src/ShellCheck/Checks/ShellSupport.hs
Most of the relevant info is already in #1429.
=> Check jobs flags in dash/POSIX sh (fixes #1429)

src/ShellCheck/Analytics.hs
Given an input like `if [[ $(a) ]]; then ...`, this is a implicit `-n` test,
so it works like `if [[ -n $(a) ]]; then ...`. Users might confuse this for
a check for the exit code of the command a, which should be tested with:
if a; then
...
We warn the user to be more explicity and specifity the `-n`.
Fixes #1416
=> Add check for ambiguous nullary test

src/ShellCheck/Fixer.hs, src/ShellCheck/Formatter/Format.hs, src/ShellCheck/Formatter/TTY.hs
WIP patch to let you see my approach to fix the tab issue in applying fix. I have more detailed message in commit d1e8c40 regarding an off-by-one error in calculating real column counts from virtual column counts.
=> Autofix tab

src/ShellCheck/Analytics.hs
https://github.com/koalaman/shellcheck/issues/1039
This change adds line number references to the case patterns for SC2221 and SC2222
Builds using the default GHC and `stack build`. I'm not sure if there's a precedent for adding tests for these kinds of changes, let me know where to add some if needed.
```shell
cat -n ~/code/shell/example.sh
1  #!/bin/bash
2
3
4  case $PATH in
5    foo)
6      echo yes
7      ;;
8    bar)
9      echo
10      ;;
11    foo)
12      echo no
13      ;;
14  esac
```
```
$ stack exec shellcheck ~/code/shell/example.sh
In /home/leaf/code/shell/example.sh line 5:
foo)
^-^ SC2221: This pattern always overrides a later one on line 11.
In /home/leaf/code/shell/example.sh line 11:
foo)
^-^ SC2222: This pattern never matches because of a previous pattern on line 5. …
```
=> Add context to case pattern warnings

src/ShellCheck/Analytics.hs
Fixes issue #1340 
I implemented this adding a `Bool` argument, but if you prefer I can separate the two functions.
I added a property using the same code you gave in the issue.
`stack test` passes cleanly.
=> Fix #1340 (SC2093 about removing "exec" should trigger in loops)

src/ShellCheck/Checks/ShellSupport.hs
=> Fix 'export -p' being undefined under POSIX sh

src/ShellCheck/Checks/ShellSupport.hs
=> Check readonly flags in dash/POSIX sh (fixes #1448)

src/ShellCheck/Checks/ShellSupport.hs
=> Check cd flags under dash & POSIX sh (fixes #1457)

src/ShellCheck/Checks/ShellSupport.hs
=> Check umask flags under dash & POSIX sh (fixes #1459)

src/ShellCheck/Checks/ShellSupport.hs
=> Check trap flags under dash & POSIX sh (fixes #1461)

src/ShellCheck/Analytics.hs
Hopefully that's enough. I followed how [SC2164 is being silenced](https://github.com/koalaman/shellcheck/blob/ec6f9e4d499c50685dc6caffcc3d4eb53320904a/src/ShellCheck/Analytics.hs#L2580).
=> Silence SC2103 when using 'set -e' (fixes #667)

src/ShellCheck/Checks/ShellSupport.hs
=> Check type flags under dash and POSIX sh (fixes #1471)

src/ShellCheck/Checks/ShellSupport.hs
Issue https://github.com/koalaman/shellcheck/issues/1330
Addresses false positives when quoted arguments to echo begin with what
looks like a flag. Now, warn only when the first argument is a
recognized echo flag and when flags are unsupported.
Second attempt, recognizes multiple flags together using regex. New test cases to verify.
```
I leaf@willow ~/w/shellcheck (issue_1330_unsupported_echo_flags=)> stack test
...
```
=> Issue 1330 unsupported echo flags

src/ShellCheck/Checks/ShellSupport.hs
The `set` builtin accepts certain flags, and some longer synonyms with `-o` under POSIX sh. Dash diverges a bit from this (adds a couple of flags, and doesn't support `-h`). Taking this into account, this makes  ShellCheck warn if any of the used flags and options are undefined, based on whether the shebang is that of POSIX sh or dash.
This fixes #990, while adding general flag-support checking for `set` in the process.
=> Check set flags under dash & POSIX sh (fixes #990)

snap/snapcraft.yaml
This pull request fixes snap building with some other miscellaneous improvements, refer each commit for details.
=> Improve snap packaging

README.md
=> docs: add Chocolatey installation method

README.md
Also adjust the tag to use the `:stable` tag mentioned in the prior
line.
=> ensure docker invocation is ephemeral

README.md
=> #1607 fixing brew command

stack.yaml
Tests pass with latest snapshot on my machine.
=> Bump stack snapshot

.compile_binaries, .prepare_deploy, .travis.yml, README.md
Hi there
I've looked for a binary for macOS, and saw this issue: https://github.com/koalaman/shellcheck/issues/1574
I'm not sure if it's the best option to compile binaries from macOS, but I did the test compiling the macOS running by Travis, but I'm not able to test the whole pipeline.
@koalaman Is it makes sense to you what I did and how could I proceed from here
=> Compiling a binary for macOS 

.compile_binaries, Dockerfile
Take full leverage of multi-stage docker build.
=> Make image build process a bit simpler

src/ShellCheck/Parser.hs
Fixes #1694
Proudly made by @gabrielelana, @sphaso and @muzietto at Open Source Saturday 
[![Open Source Saturday](https://img.shields.io/badge/%E2%9D%A4%EF%B8%8F-open%20source%20saturday-F64060.svg)](https://www.meetup.com/it-IT/Open-Source-Saturday-Milano/)
=> Parse regular `for` with body in curly braces

src/ShellCheck/Parser.hs
https://github.com/koalaman/shellcheck/issues/1731
Any literal except `esac` is valid pattern in a case statement
Build!
```
~/w/s/shellcheck (issue_1731_case_pattern_literals=)> stack build
~/w/s/shellcheck (issue_1731_case_pattern_literals=)> echo $status
0
```
Test!
```
~/w/s/shellcheck (issue_1731_case_pattern_literals=)> stack test
...
=== prop_readScript5 from src/ShellCheck/Parser.hs:3105 ===
+++ OK, passed 1 test.
ShellCheck-0.7.0: Test suite test-shellcheck passed
I leaf@alder ~/w/s/shellcheck (issue_1731_case_pattern_literals=)> echo $status
0
```
=> Issue 1731 Literals in case patterns

src/ShellCheck/Analytics.hs, src/ShellCheck/AnalyzerLib.hs, src/ShellCheck/Checker.hs, src/ShellCheck/Checks/Commands.hs, src/ShellCheck/Checks/ShellSupport.hs, src/ShellCheck/Data.hs, src/ShellCheck/Fixer.hs, src/ShellCheck/Parser.hs
Explanations for each change are in their corresponding commit messages.
=> Various cleanups and refactorings

src/ShellCheck/Analytics.hs
When adding a value containing an equals sign to an indexed array, the
left side is treated as an index if it looks like [N]=val and N is
numeric.  SC2191 currently warns about anything that looks like key=val
even though non-numeric values of key will never be treated as an index.
This causes spurious warnings for the common pattern of building up
program arguments in an array, such as:
args=(
--dry-run
--in="${my_var}"
--out=/some/path
-f
)
/bin/program "${args[@]}"
Since only numeric expressions can be a valid index for an indexed
array, only emit SC2191 if the left side of a literal string containing
an equals looks numeric.  Other more complicated constructs should still
warn because shellcheck doesn't know if they may evaluate to a numeric
result.  Associative arrays still warn …
=> SC2191: Tighten index checks

shellcheck.hs
Using filterM makes us run the monadic predicate on every list element.
Use findM instead so that we can stop once we find a matching one.
=> Use findM instead of filterM

src/ShellCheck/Analytics.hs
mumps is a compiler and parser for the M language from the gt.m.
(https://sourceforge.net/projects/fis-gtm/)
=> SC2016, repair false error for M language parser

src/ShellCheck/Analytics.hs
=> src/ShellCheck/Analytics.hs: suggest using a shell directive for SC2148

src/ShellCheck/Analytics.hs
* Avoid some unnecessary fmaps
* Reuse an identical pattern-match for two guards
* Apply De Morgan's law
* Use forM_ to avoid an unnecessary where
=> Simplify checkForInQuoted

src/ShellCheck/Analytics.hs
* Clean up usage of not
* Use a case match instead of sequence_ and a do block
=> Simplify checkWhileReadPitfalls

nextnumber, test/check_release
Fixing shellcheck warnings on shell scripts in this repo.
=> Use shellcheck on yourself

README.md
I wasn't quite sure which category to place this in, as it's technically a first-party plugin - hopefully where i've put it makes sense.
Cheers!
=> Mention the CircleCI shellcheck orb in the README.

.prepare_deploy
Reduce amount of duplicated code.
=> Simplify .prepare-deploy

src/ShellCheck/Analytics.hs
Implementing the suggestion by @pixarbuff in #1985.
=> Change error 2076 to a warning.

src/ShellCheck/Analytics.hs, src/ShellCheck/Parser.hs
For #1988
First time with Haskell, so please forgive any obvious mistakes (happy to correct with guidance) ;).
In particular, not totally sure about the prop_checkShebang bits, I tried to follow earlier conventions there.
=> add support for `/bin/busybox sh` shebang

src/ShellCheck/Analytics.hs
Fixes #2273 
This is the first time I have used Haskell for something useful so please bear with my beginner mistakes. I could not get `./quicktest` to tell me whats wrong with my checks, so some help with this would be appreciated.
Also note that this should remain a draft until [bats 1.5.0 has actually been released](https://github.com/bats-core/bats-core/issues/475).
Please also review the companion wiki pages:
- https://github.com/koalaman/shellcheck/wiki/SC2314
- https://github.com/koalaman/shellcheck/wiki/SC2315
=> bats: Add check for useless negation (SC2293)

src/ShellCheck/Analytics.hs
=> Add check for usless negation in bats

src/ShellCheck/Checks/Commands.hs
As it says on the tin. This is a common mistake that I see all over the place.
Note that you might see an "unused variable" warning for some cases of this, but (a) it's easy to accidentally ignore and (b) this is not the case for the "export readonly" variant of this mistake.
=> add SC2316: error on multiple declarations like 'readonly local'

src/ShellCheck/Checks/Commands.hs
=> Add escape characters to SC2028: \a, \b, \e, \f, \v, \\, \', \OOO, \xHH

src/ShellCheck/Analytics.hs
Resolves https://github.com/koalaman/shellcheck/issues/2563.
=> Add `mapfile` to harmless commands for SC2094

src/ShellCheck/Analytics.hs, src/ShellCheck/AnalyzerLib.hs
Resolves https://github.com/koalaman/shellcheck/issues/2537.
=> Suppress SC2311 with `set -o posix`

src/ShellCheck/Analytics.hs
Resolves https://github.com/koalaman/shellcheck/issues/2550.
@koalaman are there any commands in addition to `time` whose parsed arguments might have the `T_SimpleCommand` type? I expected `watch` and `eval` to have the same issue as `time`, but they're fine.
=> Fix false positive for SC2312 when using `time`

src/ShellCheck/Analytics.hs
=> Whitelist oc to avoid SC2016 false positive

README.md
CodeRabbit is an AI-powered code review tool that uses ShellCheck to aid its review of shell scripts.
=> Update README.md to add CodeRabbit to the list of services that use ShellCheck

README.md
Add Codety Scanner into the static analysis solution list.  
Here are the examples of the result using Shellcheck:
* Codety's pull request code review example: https://github.com/codetyio/codety-scanner/pull/66#issuecomment-2339438925
* Codety's GitHub code scan result example : https://github.com/codetyio/codety-scanner/runs/29907371258
Codety Scanner git repo: https://github.com/codetyio/codety-scanner
Added shellcheck into the credits list: https://github.com/codetyio/codety-scanner/blob/main/CREDITS.md
=> Update README.md and add Codety into the tool list
